# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_auto_20171006_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentForDjango',
            new_name='Content',
        ),
    ]
